### ISSUE TITLE
Fix rhino-pkg not indexing Flatpak

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/rhino-pkg#25]
rpk seems to have issues indexing flatpak packages due to their naming scheme.

**Comment by Elsie19** [comment]
How?

**Comment by ajstrongdev** [comment]
> How?

Well I know this was supposed to be fixed but users are apparently having issues. If you'd be able to investigate that'd be helpful @elsie19

**Comment by Elsie19** [comment]
I meant can you give examples here.

**Comment by ajstrongdev** [comment]
I don't have any, I believe the issue could've been fixed already and users have just not upgraded rpk, in which case, I can close this. I will wait a bit to see if the issue is cropped up again.

**Comment by oklopfer** [comment]
yeah we fixed this
