### ISSUE TITLE
BUG: Searching for a flatpak (stremio) with rhino-pkg yields no results

### ISSUE THREAD

**Issue by na-tt** [rhino-linux/rhino-pkg#27]
**Rhino Linux Version:**
Rhino Linux 2023.2 (mainline) x86_64

**Platform:**
x86_64 / Intel i3-4005U

**Describe the bug**
trying to install or search for stremio with rhino-pkg results in: No packages found matching 'stremio'! despite existing as a flatpak (com.stremio.Stremio) on flathub and flatpak having flathub remote setup and being able to find it directly through flatpak search

**To Reproduce**
Fresh install of Rhino linux, with flatpaks (no beta), snaps and appimage package managers installed during the setup.

>$flatpak remotes
Name Options
flathub System

>$flatpak search stremio
Name Description                                       Application ID    Version Branch Remotes
Stre...  Watch videos, movies, TV series ... ... .stremio.Stremio 4.4.160 stable  flathub

>$rhino-pkg search stremio
Searching (pacstall.../flatpak.../snap...)
No packages found matching 'stremio'!

**Expected behavior**
being able to install software through rhino-pkg if it can be found independently through flatpak, snaps, appimage, pacstall, in this case flatpak

**Comment by na-tt** [comment]
Forgot to mention i updated packages with rhino-pkg update -y after setup

**Comment by ajstrongdev** [comment]
Can you try `rhino-pkg search obsidian` and send the output here @na-tt

**Comment by ajstrongdev** [comment]
@Elsie19 Can you test both `flatpak search stremio` on AMD64 and `rpk search stremio`

**Comment by Elsie19** [comment]
```bash
elsie ~ % ››› flatpak search stremio
Name  Description                   Application ID   Version Branch Remotes
Stre… Watch videos, movies, TV ser… …stremio.Stremio 4.4.160 stable flathub
```

```bash
elsie ~ % ››› rpk search stremio
No packages found matching 'stremio'!
```

**Comment by na-tt** [comment]
> Can you try `rhino-pkg search obsidian` and send the output here @na-tt

[0]: org.gtk.Gtk3theme.Obsidian-2-Teal (flatpak)
[1]: org.gtk.Gtk3theme.Obsidian-2-Red (flatpak)
[2]: org.gtk.Gtk3theme.Obsidian-2-Purple (flatpak)
[3]: org.gtk.Gtk3theme.Obsidian-2-Mint (flatpak)
[4]: org.gtk.Gtk3theme.Obsidian-2-Indigo (flatpak)
[5]: org.gtk.Gtk3theme.Obsidian-2-Green (flatpak)
[6]: org.gtk.Gtk3theme.Obsidian-2-Gray (flatpak)
[7]: org.gtk.Gtk3theme.Obsidian-2-Aqua (flatpak)
[8]: org.gtk.Gtk3theme.Obsidian-2-Amber (flatpak)
[9]: md.obsidian.Obsidian (flatpak)
[10]: obsidian-icon-theme (apt)
[11]: obsidian-deb (pacstall)
[12]: obsidian (snap)

**Comment by oklopfer** [comment]
@na-tt Fixed. please update your rpk and try looking for stremio again so we can confirm to close the issue.

**Comment by ajstrongdev** [comment]
@oklopfer I've got my old laptop repaired and I'm installing Rhino Linux on it later. I can test this to confirm either today, or at some point within this dev cycle so we can close this.

**Comment by na-tt** [comment]
@oklopfer fixed! after rpk update i was able to search and install stremio, same with calibre wich had the same problem

**Comment by ajstrongdev** [comment]
> @oklopfer fixed! after rpk update i was able to search and install stremio, same with calibre wich had the same problem

Awesome, thank you, closing now as resolved.
