### ISSUE TITLE
BUG: Cannot get list of installed packages

### ISSUE THREAD

**Issue by Fake** [rhino-linux/rhino-pkg#28]
**Rhino Linux Version:**
2023.2

**Platform:**
Any

**Describe the bug**
For example, Apt has `list` command with `--installed` option for getting installed packages, but rpk does not have such command.
I know I can get the list by using all package manager individually, but rpk should implement that feature because Rhino Linux recommends using rpk for package management.

**To Reproduce**
Try to uninstall LibreOffice which has already installed when you installed Rhino Linux.

**Expected behavior**
Installed packages can be obtained by rpk command.

**Comment by Elsie19** [comment]
That list would be insanely long.
