### ISSUE TITLE
BUG: Removing timeshift also removes rhino-core

### ISSUE THREAD

**Issue by GjMan78** [rhino-linux/rhino-pkg#29]
**Rhino Linux Version:**
2023.2

**Platform:**
Notebook: Macbook Pro 9,2
CPU: Intel Core I5-3520m
Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q3 
Kernel: 6.5.0-060500-generic 

**Describe the bug**
I configured btrfs-assistant with snapper and wanted to remove timeshift.
When I tried I realized that continuing would uninstall the rhino-core metapackage and the next update would remove many essential packages.

`apt info -a rhino-core`
`Package: rhino-core
Version: 2023.2-pacstall2
Status: install ok installed
Priority: optional
Section: Pacstall
Maintainer: Oren Klopfer <oren@taumoda.com>
Installed-Size: 1.024 B
Depends: com.github.libredeb.lightpad, papirus-folders, ulauncher, rhino-pkg, unicorn-desktop, rhino-kvantum-theme, rhino-plymouth-theme, rhino-pkg, rhino-neofetch, rhino-system, timeshift
Conflicts: rhino-pine-core, rhino-server-core
Replace: rhino-pine-core, rhino-server-core
Download-Size: sconosciuto
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Transitional package to provide all core Rhino Linux software`

**To Reproduce**
Just simply run this:
`rpk remove timeshift`

**Expected behavior**
It would be useful to be able to remove timeshift without destroying the system!

**Comment by ajstrongdev** [comment]
@oklopfer Considering this is optional software shouldn't it become preinstalled via the builder, and then removed as a pacdep?

**Comment by oklopfer** [comment]
> @oklopfer Considering this is optional software shouldn't it become preinstalled via the builder, and then removed as a pacdep? 

Sure, I can drop it from core dependencies and move it to the iso instead. We had added it as a dep so 2023.1 + 2023.2 users would receive the default install OTA. But now that we are far enough beyond and people have updated, we can move where it is installed.

**Comment by oklopfer** [comment]
https://github.com/pacstall/pacstall-programs/commit/c75f8ead48c15a4246ad72faee15c66349a31946
