### ISSUE TITLE
Fix: Revert nala to use full-upgrade

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/rhino-pkg#32]
Changes in Nala v0.14.0 have affected how upgrades are handled. 

The `sudo nala update` function that rhino-pkg utilises no-longer automatically removes packages, nor performs full-scale upgrades which is vital for when Ubuntu update their devel base.

**Comment by oklopfer** [comment]
With this, we are gunna need an interim version check, while waiting for users to upgrade. 

if nala <=0.13 use upgrade, if nala >=0.14 use full-upgrade

**Comment by ajstrongdev** [comment]
> With this, we are gunna need an interim version check, while waiting for users to upgrade. 

Completely agree. Can we also remember to tag this release as rhino-pkg v0.1.2 since we forgot to tag v0.1.1 last time irrc 🙏

**Comment by ajstrongdev** [comment]
Perfect, I will work on this ASAP. 

Probably will take 3 hours before I can.

**Comment by oklopfer** [comment]
We can and should pass `sudo nala upgrade --full --no-autoremove` 

It causes too many issues for users having stuff be removed when we drop it from a dependency (it is then set to auto-installed, meaning it’ll remove those things, and they may want to keep them), if anything we should add a `--hard`-type flag for when it *should* auto-remove
