### ISSUE TITLE
BUG: Balena-etcher doesn't install

### ISSUE THREAD

**Issue by MarioInJapan** [rhino-linux/rhino-pkg#41]
**Rhino Linux Version:**
2023.4

**Platform:**
INTEL 

**Describe the bug**
Balena-etcher is offered by Bacstall for installation, but it doesn't install because of "unmet dependencies".

**To Reproduce**
1. rpk install balena-etcher
2. Click on 0 balena-etcher (Pacinstal)
3. Error "Failed to install package balena-etcher-deb"

**Expected behavior**
If an option to install the package is available, the package should be installed without errors.

**Additional context**
I see that Balena isn't available in Synaptic either as Deb package.

**Comment by Elsie19** [comment]
What error does it give.

**Comment by ajstrongdev** [comment]
try update with rpk update, then `sudo apt --fix-broken install`
