### ISSUE TITLE
Feature Request: cli flag to change the default y/N response

### ISSUE THREAD

**Issue by iconoclasthero** [rhino-linux/rhino-pkg#44]
The confirmation for accepting packages is backwards for _me_ after more than a decade of installing with apt.  I am expecting to just confirm it once I see it, not have to actually find the y key and hit it.  I would like to alias rpk to rpk --confirm=Y so that I can just hit enter the way that I've been doing with apt for over a decade.

**Comment by oklopfer** [comment]
Can’t you just use the `-y` flag?

**Comment by iconoclasthero** [comment]
That does not do the same thing, that takes away all ability to confirm.  Instead of reviewing and hitting enter, it installs automatically, which, again, is a departure from how I've been installing packages since probably Ubuntu 8 but at least 10.

Anyway, I see this is in bash, apologies, I'll make my own fork.

**Comment by iconoclasthero** [comment]
Hey, one thing I thought about... what about this wrapping pipx?

**Comment by iconoclasthero** [comment]
Also, is there some way in rpk/pacstall to `apt-mark` packages to not up updated now that I have a different `rhino-pkg`?

**Comment by oklopfer** [comment]
Not directly, though this is a feature to consider. Your easiest way around this is to set the pkgver to a high number so that it is always recognized as the latest version.
