### ISSUE TITLE
Can't install multiple packages

### ISSUE THREAD

**Issue by ajgringo619** [rhino-linux/rhino-pkg#50]
Fairly new to this project, so I'm sure I'm missing something simple. When running an install command with multiple packages:
```
rpk install nfs-common apt-file fonts-open-sans
```
it always fails with:
```
No packages found matching 'nfs-common apt-file fonts-open-sans'!
```
I found nothing in the man page that would indicate that this is normal behavior.

**Comment by Elsie19** [comment]
That is intended behavior. If not, the output would balloon in size and not be user-friendly in that sense.

**Comment by ajgringo619** [comment]
OK, that makes sense.
